apiVersion: v1
kind: Service
metadata:
  name: im-push-service
  labels:
    app: im-push
    service: im-push-service
spec:
  clusterIP: None
  selector:
    app: im-push
  ports:
    - name: grpc
      protocol: TCP
      port: 10170
      targetPort: 10170
    - name: prometheus
      protocol: TCP
      port: 12170
      targetPort: 12170
