apiVersion: v1
kind: Secret
metadata:
  name: mysqld-exporter-secret
  namespace: monitoring
type: Opaque
data:
  DATA_SOURCE_NAME: "aW1XYWxsZXQ6MW1XNGxsZTN0U3RhZzIwMjVAKHJtLWQ5anNkODllZG4zNDU5Y2UyLm15c3FsLmFwLXNvdXRoZWFzdC01LnJkcy5hbGl5dW5jcy5jb206MzMwNikv"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  namespace: monitoring
  labels:
    app: mysqld-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  template:
    metadata:
      labels:
        app: mysqld-exporter
    spec:
      containers:
        - name: mysqld-exporter
          image: prom/mysqld-exporter:v0.15.1
          ports:
            - name: metrics
              containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: mysqld-exporter-secret
                  key: DATA_SOURCE_NAME
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: monitoring
  labels:
    app: mysqld-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9104
      targetPort: 9104
  selector:
    app: mysqld-exporter
