apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rpc-group-service
  labels:
    app: rpc-group
    service: im-rpc-group
spec:
  serviceName: rpc-group-service
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  replicas: 1
  selector:
    matchLabels:
      app: rpc-group
  template:
    metadata:
      labels:
        app: rpc-group
        service: im-rpc-group
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: im-rpc-group
          image: akachat/server
          imagePullPolicy: Always
          env:
            - name: DEBUG_MODE
              value: "true"
            - name: CONFIG_PATH
              value: "/config"
            - name: IMENV_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: IMENV_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_username
            - name: IMENV_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_password
          volumeMounts:
            - name: server-config
              mountPath: "/config"
              readOnly: true
            - name: srv-log
              mountPath:  "/akachat/server/logs"
          ports:
            - name: grpc
              containerPort: 10260
            - name: prometheus
              containerPort: 12260
            - name: debug
              containerPort: 2345
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
          livenessProbe:
            tcpSocket:
              port: 10260
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 10260
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: server-config
          configMap:
            name: server-config
        - name: srv-log
          persistentVolumeClaim:
            claimName: cnfs-nas-pvc
