apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base
patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: wallet-msgtransfer
      namespace: default # 关键：和 overlay 的 namespace 一致
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          alibabacloud.com/nodepool-id: npa34ac756a1b042f2ad17d64918562096
images:
  - name: akachat/server
    newTag: 3-merge-9b887206-198dbb1
    newName: ghcr.io/1nterdigital/aka-wallet-msgtransfer
