apiVersion: v1
kind: Service
metadata:
  name: chat-rpc-service
spec:
  selector:
    app: chat-rpc
  ports:
    - name: grpc
      protocol: TCP
      port: 30300
      targetPort: 30300
    - name: debug
      protocol: TCP
      port: 2345
      targetPort: 2345
  clusterIP: None