apiVersion: v1
kind: Secret
metadata:
  name: openim-mongo-secret
  namespace: default
type: Opaque
data:
  mongo_initdb_root_username: cm9vdA== # base64 for "root", this user credentials need in authSource database.
  mongo_initdb_root_password: TldXRjE1SzFWekFLNDBuZQ==  # base64 for "NWWF15K1VzAK40ne"
  mongo_initdb_database: b3BlbmltX3Yz # base64 for "openim_v3", this database will be created.
  mongo_openim_username: b3BlbklN # base64 for "openIM", this user credentials need in openim_v3 database.
  mongo_openim_password: Qm5OdjJNa3p1OUVT  # base64 for "BnNv2Mkzu9ES", this user credentials need in
  mongo_primary_host: ZGRzLWQ5ajM5OWVlMDA2NDdlNzQxLm1vbmdvZGIuYXAtc291dGhlYXN0LTUucmRzLmFsaXl1bmNzLmNvbTozNzE3Cg== # base64 for "dds-d9j399ee00647e741.mongodb.ap-southeast-5.rds.aliyuncs.com:3717"
  mongo_secondary_host: ZGRzLWQ5ajM5OWVlMDA2NDdlNzQyLm1vbmdvZGIuYXAtc291dGhlYXN0LTUucmRzLmFsaXl1bmNzLmNvbTozNzE3Cg== # base64 for "dds-d9j399ee00647e742.mongodb.ap-southeast-5.rds.aliyuncs.com:3717"
  mongo_replica_set: cmVwbGljYVNldD1tZ3NldC0xMTA3ODA1MjM5 # base64 for "replicaSet=mgset-1107805239", this value need in mongodb connection string if using replica set.