apiVersion: v1
kind: Service
metadata:
  name: rpc-user-service
  labels:
    app: rpc-user
    service: rpc-user-service
spec:
  clusterIP: None
  selector:
    app: rpc-user
  ports:
    - name: grpc
      protocol: TCP
      port: 10320
      targetPort: 10320
    - name: prometheus
      protocol: TCP
      port: 12320
      targetPort: 12320
    - name: debug
      protocol: TCP
      port: 2345
      targetPort: 2345
