apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rpc-user
  labels:
    app: rpc-user
    service: rpc-user-service
spec:
  serviceName: rpc-user-service
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  replicas: 1
  selector:
    matchLabels:
      app: rpc-user
  template:
    metadata:
      labels:
        app: rpc-user
        service: rpc-user-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: rpc-user
          image: akachat/server # <-- 关键修复：使用逻辑名称，与 kustomization.yml 中的 name 字段匹配
          imagePullPolicy: Always
          env:
            - name: DEBUG_MODE
              value: "true"
            - name: CONFIG_PATH
              value: "/config"
            - name: IMENV_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: IMENV_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_username
            - name: IMENV_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_password
            - name: IMENV_KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-kafka-secret
                  key: kafka-password
          volumeMounts:
            - name: server-config
              mountPath: "/config"
              readOnly: true
            - name: srv-log
              mountPath: "/akachat/server/logs"
          ports:
            - name: grpc
              containerPort: 10320
            - name: prometheus
              containerPort: 12320
            - name: debug
              containerPort: 2345
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
          livenessProbe:
            tcpSocket:
              port: 10320
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 10320
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: server-config
          configMap:
            name: server-config
        - name: srv-log
          persistentVolumeClaim:
            claimName: cnfs-nas-pvc
