apiVersion: v1
kind: Service
metadata:
  name: etcd-cluster-lb
  namespace: component
  labels:
    app: etcd-cluster
  annotations:
    # 使用经典负载均衡器（CLB）- 配置简单
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"
    # 面向互联网的负载均衡器
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    # 启用跨可用区负载均衡
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    # 后端协议
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    # 健康检查配置
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "traffic-port"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    # 连接设置
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "350"
spec:
  type: LoadBalancer
  selector:
    app: etcd-cluster
  ports:
    - name: client
      port: 2379
      targetPort: 2379
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
