apiVersion: v1
kind: Service
metadata:
  name: etcd-headless
  namespace: component
  labels:
    app: etcd-cluster
spec:
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: etcd-cluster