apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd-cluster
  namespace: component
spec:
  serviceName: etcd-headless
  replicas: 3  # etcd集群：3个节点
  selector:
    matchLabels:
      app: etcd-cluster
  template:
    metadata:
      labels:
        app: etcd-cluster
    spec:
      containers:
        - name: etcd
          image: bitnami/etcd:3.5-debian-12
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          env:
            - name: ETCD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_DATA_DIR
              value: /etcd-data
            - name: ETCD_LISTEN_CLIENT_URLS
              value: http://0.0.0.0:2379
            - name: ETCD_LISTEN_PEER_URLS
              value: http://0.0.0.0:2380
            - name: ETCD_INITIAL_CLUSTER
              value: etcd-cluster-0=http://etcd-cluster-0.etcd-headless.component.svc.cluster.local:2380,etcd-cluster-1=http://etcd-cluster-1.etcd-headless.component.svc.cluster.local:2380,etcd-cluster-2=http://etcd-cluster-2.etcd-headless.component.svc.cluster.local:2380
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: etcd-cluster-token
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: new
            - name: ETCD_AUTO_COMPACTION_MODE
              value: periodic
            - name: ETCD_AUTO_COMPACTION_RETENTION
              value: "1"
          command:
            - /bin/bash
            - -c
            - |
              export ETCD_ADVERTISE_CLIENT_URLS=http://${ETCD_NAME}.etcd-headless.component.svc.cluster.local:2379
              export ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${ETCD_NAME}.etcd-headless.component.svc.cluster.local:2380
              exec /opt/bitnami/scripts/etcd/entrypoint.sh /opt/bitnami/scripts/etcd/run.sh
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd-data
          readinessProbe:
            tcpSocket:
              port: 2379
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 2379
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: alicloud-disk-essd
        resources:
          requests:
            storage: 20Gi
