apiVersion: v1
kind: Service
metadata:
  name: chat-api-service
spec:
  selector:
    app: chat-api
  ports:
    - name: http
      protocol: TCP
      port: 10008
      targetPort: 10008
    - name: debug
      protocol: TCP
      port: 2345
      targetPort: 2345
  clusterIP: None