apiVersion: v1
kind: Service
metadata:
  name: admin-rpc-service
spec:
  selector:
    app: admin-rpc
  ports:
    - name: grpc
      protocol: TCP
      port: 30200
      targetPort: 30200
    - name: debug
      protocol: TCP
      port: 2345
      targetPort: 2345
  clusterIP: None