apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: admin-rpc-service
  labels:
    app: admin-rpc
    service: admin-rpc-service
spec:
  serviceName: admin-rpc-service
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  replicas: 1
  selector:
    matchLabels:
      app: admin-rpc
  template:
    metadata:
      labels:
        app: admin-rpc
        service: admin-rpc-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: admin-rpc
          image: akachat/server
          imagePullPolicy: Always
          env:
            - name: DEBUG_MODE
              value: "true"
            - name: CONFIG_PATH
              value: "/config"
            - name: CHATENV_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: CHATENV_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_username
            - name: CHATENV_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-mongo-secret
                  key: mongo_openim_password

          volumeMounts:
            - name: chat-config
              mountPath: "/config"
              readOnly: true
            - name: srv-log
              mountPath:  "/akachat/server/logs"
          ports:
            - name: grpc
              containerPort: 30200
            - name: debug
              containerPort: 2345
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
          livenessProbe:
            tcpSocket:
              port: 30200
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 30200
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: chat-config
          configMap:
            name: chat-config
        - name: srv-log
          persistentVolumeClaim:
            claimName: cnfs-nas-pvc
