apiVersion: v1
kind: Service
metadata:
  name: im-msggateway-external
  labels:
    app: im-msggateway
    service: im-msggateway-external
spec:
  type: ClusterIP
  selector:
    app: im-msggateway
  ports:
    - name: http-websocket
      protocol: TCP
      port: 10001
      targetPort: 10001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: im-msggateway-alb
  namespace: default
  annotations: 

    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    # 更改健康检查路径，避免与WebSocket端点冲突
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
    external-dns.alpha.kubernetes.io/hostname: ws1.0dev.cc
spec:
  ingressClassName: alb
  rules:
    - host: ws1.0dev.cc
      http:
        paths:
          # 明确指定WebSocket路径
          - path: /
            pathType: Prefix
            backend:
              service:
                name: im-msggateway-external
                port:
                  number: 10001
          # 可选：为其他HTTP请求添加路径
          - path: /
            pathType: Prefix
            backend:
              service:
                name: im-msggateway-external
                port:
                  number: 10001
  tls:
    - hosts:
      - ws1.0dev.cc