apiVersion: v1
kind: Service
metadata:
  name: admin-api-service
spec:
  selector:
    app: admin-api
  ports:
    - name: debug
      protocol: TCP
      port: 2345
      targetPort: 2345
  clusterIP: None