apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: default
type: Opaque
data:
  minio-root-user: bWluaW9hZG1pbg== # Base64 encoded "minioadmin"
  minio-root-password: bWluaW9hZG1pbjEyMw== # Base64 encoded "minioadmin123"